"""Build the independent release section from Markdown with TOML metadata."""

import argparse
from datetime import date
from html import escape
from pathlib import Path
import re
from string import Template
import sys
import tomllib

try:
    import markdown
except ImportError:
    sys.exit("Install dependencies: python -m pip install -r tools/releases/requirements.txt")

ROOT = Path(__file__).resolve().parents[2]
RELEASES = ROOT / "releases"
SITE_URL = "https://sioaeko.github.io/scriptplayer-plus-docs/releases/"
MARKER = "<!-- Generated by tools/releases/build.py. -->"
DESCRIPTION = "새 버전의 주요 변경 사항과 업데이트 안내를 전합니다."
TEMPLATE = Template(Path(__file__).with_name("page.html").read_text(encoding="utf-8"))


def read_posts(source):
    posts = []
    for path in sorted(source.glob("*.md")):
        try:
            raw = path.read_text(encoding="utf-8-sig")
            match = re.fullmatch(r"\+\+\+\n(.*?)\n\+\+\+\n(.*)", raw, re.S)
            if not match:
                raise ValueError("Start with TOML metadata between +++ lines.")
            meta = tomllib.loads(match[1])
            if type(meta.get("draft")) is not bool:
                raise ValueError("draft must be true or false.")
            if meta["draft"]:
                continue
            slug = path.stem
            if not re.fullmatch(r"[a-z0-9]+(?:[.-][a-z0-9]+)*", slug) or slug in {"index", "404"}:
                raise ValueError("Use a lowercase filename such as v1.2.3.md (not index or 404).")
            for field in ("title", "summary"):
                if not isinstance(meta.get(field), str) or not meta[field].strip():
                    raise ValueError(f"{field} must be a nonempty string.")
                meta[field] = meta[field].strip()
            if type(meta.get("date")) is not date:
                raise ValueError("date must be an unquoted date: YYYY-MM-DD.")
            if not isinstance(meta.get("version", ""), str):
                raise ValueError("version must be a string, or omitted for general notices.")
            if not match[2].strip():
                raise ValueError("Published announcements need a body.")
            meta.update(slug=slug, body=markdown.markdown(match[2], extensions=["fenced_code", "sane_lists"]))
            if re.search(r"<h1(?:\s|>)", meta["body"], re.I):
                raise ValueError("The title is rendered automatically. Start body headings at ##.")
            posts.append(meta)
        except (ValueError, OSError) as error:
            raise ValueError(f"{path.name}: {error}") from error
    return sorted(posts, key=lambda p: (p["date"], p["slug"]), reverse=True)


def metadata(post):
    day = post["date"]
    version = escape(post.get("version", "").strip())
    label = f'<span class="version">{version}</span>' if version else ""
    return (f'<div class="release-meta"><time datetime="{day.isoformat()}">'
            f'{day.year}.{day.month:02}.{day.day:02}</time>{label}</div>')


def page(title, description, filename, content):
    return TEMPLATE.substitute(
        title=escape(title), description=escape(description),
        url=SITE_URL + ("" if filename == "index.html" else filename),
        og_type="website" if filename == "index.html" else "article",
        current='aria-current="page"' if filename == "index.html" else 'aria-current="true"',
        content=content,
    )


def render(source=RELEASES / "posts"):
    posts = read_posts(source)
    heading = f'''      <header class="page-heading">
        <h1>릴리스 공지</h1>
        <p class="intro">{DESCRIPTION}</p>
      </header>'''
    if posts:
        rows = []
        for post in posts:
            rows.append(f'''        <li>
          <a class="release-link" href="{post['slug']}.html">
            {metadata(post)}
            <div><h2>{escape(post['title'])}</h2><p>{escape(post['summary'])}</p></div>
            <span class="release-arrow" aria-hidden="true">→</span>
          </a>
        </li>''')
        listing = '      <ol class="release-list" aria-label="최신순 공지 목록">\n' + "\n".join(rows) + '\n      </ol>'
    else:
        listing = '''      <section class="empty-state" aria-labelledby="empty-title">
        <svg class="empty-icon" viewBox="0 0 38 44" fill="none" aria-hidden="true">
          <path d="M9 3h14l8 8v28H7V3h2Z M23 3v9h8 M13 21h12 M13 28h8" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round" stroke-linecap="round" />
        </svg>
        <div>
          <h2 id="empty-title">아직 등록된 공지가 없습니다</h2>
          <p>새 공지가 등록되면 이곳에서 확인할 수 있습니다.</p>
          <a class="text-link" href="https://github.com/sioaeko/scriptplayer-plus/releases">공개된 버전은 GitHub에서 확인하기 <span aria-hidden="true">↗</span></a>
        </div>
      </section>'''
    pages = {"index.html": page("릴리스 공지 · ScriptPlayer+", DESCRIPTION, "index.html", heading + "\n" + listing)}
    for post in posts:
        filename = post["slug"] + ".html"
        content = f'''      <div class="article-wrap">
        <a class="back-link" href="./"><span aria-hidden="true">←</span> 전체 공지</a>
        <article>
          <header class="article-header">
            {metadata(post)}
            <h1>{escape(post['title'])}</h1>
            <p class="intro">{escape(post['summary'])}</p>
          </header>
          <div class="prose">
{post['body']}
          </div>
        </article>
        <nav class="article-end" aria-label="공지 탐색">
          <a class="back-link" href="./"><span aria-hidden="true">←</span> 전체 공지로 돌아가기</a>
        </nav>
      </div>'''
        pages[filename] = page(post["title"] + " · ScriptPlayer+", post["summary"], filename, content)
    return pages


def write_pages(pages, output=RELEASES, check=False):
    output = output.resolve()
    existing = {}
    for path in output.glob("*.html"):
        if path.is_symlink() or path.resolve().parent != output:
            raise ValueError(f"Refusing to modify linked page: {path}")
        existing[path.name] = path.read_text(encoding="utf-8")
    for name in pages:
        if name in existing and MARKER not in existing[name]:
            raise ValueError(f"Refusing to overwrite a manually written page: {name}")
    stale = [name for name, content in existing.items() if MARKER in content and name not in pages]
    changed = [name for name, content in pages.items() if existing.get(name) != content]
    if check:
        if stale or changed:
            raise ValueError("Generated pages are out of date. Run python tools/releases/build.py")
        return
    output.mkdir(parents=True, exist_ok=True)
    for name in changed:
        (output / name).write_text(pages[name], encoding="utf-8", newline="\n")
    # Remove only this generator's obsolete HTML files in this exact directory.
    for name in stale:
        (output / name).unlink()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Verify generated HTML without writing files")
    args = parser.parse_args()
    try:
        pages = render()
        write_pages(pages, check=args.check)
    except (ValueError, OSError) as error:
        parser.exit(1, f"Error: {error}\n")
    print(f"{'Checked' if args.check else 'Built'} {len(pages) - 1} announcements and releases/index.html")


if __name__ == "__main__":
    main()
